from typing import Union
from pydantic import BaseModel

class Artifact(BaseModel):
    """Structured data generated by agents (CSV, PDF text, JSON)."""
    # artifact_id: str # We'll want to reference artifacts across tasks
    artifact_type: str # helps downstream agents decide how to interpret the content.
    task_id: int
    source: str
    content: Union[str, dict]
    timestamp: str
