# mcp_servers/search/server.py
import httpx
import os
import logging
import sys

from pydantic import BaseModel
from mcp.server.fastmcp import FastMCP
from datetime import datetime, timezone


# Configure logging to show internal MCP message routing
logging.basicConfig(
    level=logging.DEBUG,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
    stream=sys.stderr
)

# You can specifically target the MCP server logger for less noise
logging.getLogger("mcp.server").setLevel(logging.DEBUG)
logging.getLogger("fastmcp").setLevel(logging.DEBUG)


class ResearchTool(BaseModel):
    """Structured data generated by agents (CSV, PDF text, JSON)."""
    source: str
    content: str | dict
    success: bool = True
    error: str | None = None
    timestamp: str
    

# Create the server
mcp = FastMCP("InvestmentResearch", host="0.0.0.0", port=3000)

@mcp.tool()
async def search_market_data(query: str) -> ResearchTool:
    """
    Search the web for real-time investment data, SEC filings, and news.
    Returns a structured artifact.
    """
    api_key = os.getenv("TAVILY_API_KEY")

    try:
        async with httpx.AsyncClient(timeout=30.0) as client:
            response = await client.post(
                "https://api.tavily.com/search",
                json={
                    "api_key": api_key, 
                    "query": query, 
                    "search_depth": "advanced",
                    "max_results": 5
                },
            )
            response.raise_for_status()
            data = response.json()
            results = [f"Source: {r['url']}\nContent: {r['content']}" 
                       for r in data.get("results", [])]

            content = "\n\n---\n\n".join(results) if results else "No relevant results found."

            return ResearchTool(
                source="Tavily API",
                content=content,
                success=True,
                error=None,
                timestamp=datetime.now(timezone.utc).isoformat(),
            )

    except Exception as e:
        return ResearchTool(
            source="Tavily API",
            content="",
            success=False,
            error=str(e),
            timestamp=datetime.now(timezone.utc).isoformat()
        )

if __name__ == "__main__":
    mcp.run(
        transport="streamable-http",
    )