from typing import Union, Literal
from pydantic import BaseModel

class Artifact(BaseModel):
    """Structured data generated by agents (CSV, PDF text, JSON)."""
    artifact_type: str # helps downstream agents decide how to interpret the content.
    task_id: int
    source: Literal["research", "analyst", "quant_analyst", "vector_db"]
    content: Union[str, dict]
    success: bool = True
    error: str | None = None
    timestamp: str