from typing import Union, List
from pydantic import BaseModel

class Artifact(BaseModel):
    """Structured data generated by agents (CSV, PDF text, JSON)."""
    # artifact_id: str # references artifacts across tasks
    artifact_type: str # helps downstream agents decide how to interpret the content.
    task_id: int
    source: str
    content: Union[str, dict]
    success: bool = True
    error: str | None = None
    timestamp: str